"""PRD1C3B2B2 constants for verified migration transactions."""

from __future__ import annotations

MIGRATIONS_DIRNAME = "migrations"
MIGRATION_PLAN_SCHEMA_VERSION = 1
MIGRATION_EVENT_SCHEMA_VERSION = 1
MIGRATION_RESULT_SCHEMA_VERSION = 1
MIGRATION_RECOVERY_PLAN_SCHEMA_VERSION = 1
MIGRATION_RESOLUTION_SCHEMA_VERSION = 1

MIGRATION_PLAN_NAME = "plan.json"
MIGRATION_RESULT_NAME = "result.json"
MIGRATION_EVENTS_DIRNAME = "events"
MIGRATION_RECOVERIES_DIRNAME = "recoveries"
MIGRATION_RESOLUTION_NAME = "resolution.json"

# Migration journal phases (event / in-memory status)
STATUS_MIGRATION_PLANNED = "planned"
STATUS_MIGRATION_BACKUP_STARTED = "backup_started"
STATUS_MIGRATION_BACKUP_VERIFIED = "backup_verified"
STATUS_MIGRATION_HOLD_ACQUIRED = "hold_acquired"
STATUS_MIGRATION_PRE_MIGRATION_REVALIDATED = "pre_migration_revalidated"
STATUS_MIGRATION_STARTED = "migration_started"
STATUS_MIGRATION_COMMAND_COMPLETED = "migration_command_completed"
STATUS_MIGRATION_TARGET_HEADS_VERIFIED = "target_heads_verified"
STATUS_MIGRATION_APPLICATION_STABILIZED = "application_stabilized"
STATUS_MIGRATION_STATE_COMMITTED = "state_committed"
STATUS_MIGRATION_COMMITTED = "committed"
STATUS_MIGRATION_FAILED = "failed"
STATUS_MIGRATION_REQUIRES_RECOVERY = "migration_requires_recovery"

PRE_MUTATION_PHASES = frozenset(
    {
        STATUS_MIGRATION_PLANNED,
        STATUS_MIGRATION_BACKUP_STARTED,
        STATUS_MIGRATION_BACKUP_VERIFIED,
        STATUS_MIGRATION_HOLD_ACQUIRED,
        STATUS_MIGRATION_PRE_MIGRATION_REVALIDATED,
    }
)

MIGRATION_LEGAL_TRANSITIONS: dict[str, frozenset[str]] = {
    STATUS_MIGRATION_PLANNED: frozenset(
        {STATUS_MIGRATION_BACKUP_STARTED, STATUS_MIGRATION_FAILED}
    ),
    STATUS_MIGRATION_BACKUP_STARTED: frozenset(
        {STATUS_MIGRATION_BACKUP_VERIFIED, STATUS_MIGRATION_FAILED}
    ),
    STATUS_MIGRATION_BACKUP_VERIFIED: frozenset(
        {STATUS_MIGRATION_HOLD_ACQUIRED, STATUS_MIGRATION_FAILED}
    ),
    STATUS_MIGRATION_HOLD_ACQUIRED: frozenset(
        {STATUS_MIGRATION_PRE_MIGRATION_REVALIDATED, STATUS_MIGRATION_FAILED}
    ),
    STATUS_MIGRATION_PRE_MIGRATION_REVALIDATED: frozenset(
        {STATUS_MIGRATION_STARTED, STATUS_MIGRATION_FAILED}
    ),
    STATUS_MIGRATION_STARTED: frozenset(
        {
            STATUS_MIGRATION_COMMAND_COMPLETED,
            STATUS_MIGRATION_REQUIRES_RECOVERY,
        }
    ),
    STATUS_MIGRATION_COMMAND_COMPLETED: frozenset(
        {
            STATUS_MIGRATION_TARGET_HEADS_VERIFIED,
            STATUS_MIGRATION_REQUIRES_RECOVERY,
        }
    ),
    STATUS_MIGRATION_TARGET_HEADS_VERIFIED: frozenset(
        {
            STATUS_MIGRATION_APPLICATION_STABILIZED,
            STATUS_MIGRATION_REQUIRES_RECOVERY,
        }
    ),
    STATUS_MIGRATION_APPLICATION_STABILIZED: frozenset(
        {
            STATUS_MIGRATION_STATE_COMMITTED,
            STATUS_MIGRATION_REQUIRES_RECOVERY,
        }
    ),
    STATUS_MIGRATION_STATE_COMMITTED: frozenset({STATUS_MIGRATION_COMMITTED}),
    STATUS_MIGRATION_FAILED: frozenset(),
    STATUS_MIGRATION_REQUIRES_RECOVERY: frozenset(),
    STATUS_MIGRATION_COMMITTED: frozenset(),
}

MIGRATION_TERMINAL_STATUSES = frozenset(
    {
        STATUS_MIGRATION_COMMITTED,
        STATUS_MIGRATION_FAILED,
        STATUS_MIGRATION_REQUIRES_RECOVERY,
    }
)

MIGRATION_RECOVERY_OUTCOME_ACCEPT_SOURCE = "accept_source"
MIGRATION_RECOVERY_OUTCOME_ACCEPT_TARGET = "accept_target"
MIGRATION_RECOVERY_OUTCOME_RELEASE_HOLD = "release_hold"

MIGRATION_TEST_PROJECT_PREFIX = "fetchnow-migration-test-"

LABEL_MIGRATION_ID = "com.fetchnow.migration-id"
LABEL_MIGRATION_REVISION = "com.fetchnow.migration-revision"

HOLDS_DIRNAME = "holds"
HOLD_ACQUIRED_NAME = "acquired.json"
HOLD_RELEASED_NAME = "released.json"
HOLD_SCHEMA_VERSION = 1
