"""Compose override that pins application services to immutable image IDs."""

from __future__ import annotations

import re
from pathlib import Path

from .c3_constants import (
    APPLICATION_SERVICES,
    IMAGES_OVERRIDE_NAME,
    LABEL_DEPLOYMENT_ID,
    LABEL_RELEASE_REVISION,
    RUNTIME_APPLICATION_SERVICES,
)
from .journal_io import JournalIOError, atomic_write_text
from .manifest import ImageRecord, ReleaseManifest

_IMAGE_ID_RE = re.compile(r"^sha256:[0-9a-f]{64}$")
_DELIVERY_SERVICE_RE = re.compile(r"(?m)^  delivery:\s*(?:#.*)?$")
_STORAGE_INIT_SERVICE_RE = re.compile(r"(?m)^  storage-init:\s*(?:#.*)?$")


class OverrideError(ValueError):
    """Invalid image override generation."""


def compose_files_include_delivery(compose_files: tuple[Path, ...]) -> bool:
    """Return whether a verified Compose source declares the PR7 service.

    Older prepared releases (through PR6) intentionally lack delivery. This
    keeps rollback/recovery from introducing a phantom service through an
    override file alone.
    """
    for path in compose_files:
        try:
            if path.name == "compose.yaml" and _DELIVERY_SERVICE_RE.search(
                path.read_text(encoding="utf-8")
            ):
                return True
        except OSError:
            continue
    return False


def compose_files_include_storage_init(compose_files: tuple[Path, ...]) -> bool:
    """Return whether a verified Compose source declares the PR9 oneshot.

    Older prepared releases (through PR8) intentionally lack storage-init.
    Rollback/recovery must not introduce a phantom oneshot via override alone.
    """
    for path in compose_files:
        try:
            if path.name == "compose.yaml" and _STORAGE_INIT_SERVICE_RE.search(
                path.read_text(encoding="utf-8")
            ):
                return True
        except OSError:
            continue
    return False


def image_ids_from_manifest(manifest: ReleaseManifest) -> dict[str, str]:
    """Map api/web/gateway (+ worker=api) to immutable Docker image IDs."""
    by_svc = {img.service: img.image_id for img in manifest.images}
    for svc in ("api", "web", "gateway"):
        if svc not in by_svc:
            raise OverrideError(f"manifest missing image for {svc}")
        if not _IMAGE_ID_RE.fullmatch(by_svc[svc]):
            raise OverrideError(f"malformed image ID for {svc}: {by_svc[svc]!r}")
    return {
        "api": by_svc["api"],
        "worker": by_svc["api"],
        "web": by_svc["web"],
        "gateway": by_svc["gateway"],
    }


def records_by_service(manifest: ReleaseManifest) -> dict[str, ImageRecord]:
    return {img.service: img for img in manifest.images}


def render_images_override(
    image_ids: dict[str, str],
    *,
    deployment_id: str | None = None,
    release_revision: str | None = None,
    include_delivery: bool = False,
    include_storage_init: bool = False,
) -> str:
    """Render a Compose override pinning app services; excludes postgres."""
    for svc in APPLICATION_SERVICES:
        if svc not in image_ids:
            raise OverrideError(f"missing image ID for {svc}")
        if not _IMAGE_ID_RE.fullmatch(image_ids[svc]):
            raise OverrideError(f"malformed image ID for {svc}")
    if image_ids["api"] != image_ids["worker"]:
        raise OverrideError("api and worker image IDs must be identical")
    if "postgres" in image_ids:
        raise OverrideError("postgres must not appear in application image override")
    if (deployment_id is None) != (release_revision is None):
        raise OverrideError(
            "deployment_id and release_revision must both be set or both omitted"
        )
    if deployment_id is not None:
        import re as _re

        if not _re.fullmatch(
            r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
            deployment_id,
        ):
            raise OverrideError(f"malformed deployment_id for labels: {deployment_id!r}")
        if not _re.fullmatch(r"^[0-9a-f]{40}$", release_revision or ""):
            raise OverrideError(
                f"malformed release_revision for labels: {release_revision!r}"
            )

    lines = [
        "# Generated by FetchNow PRD1C3A — immutable image activation.",
        "# Do not edit. Pins application services only.",
        "services:",
    ]
    runtime_services = tuple(
        svc
        for svc in RUNTIME_APPLICATION_SERVICES
        if svc != "delivery" or include_delivery
    )
    for svc in runtime_services:
        image_key = "api" if svc == "delivery" else svc
        lines.append(f"  {svc}:")
        lines.append(f"    image: {image_ids[image_key]}")
        lines.append("    pull_policy: never")
        if deployment_id is not None and release_revision is not None:
            lines.append("    labels:")
            lines.append(f"      {LABEL_DEPLOYMENT_ID}: \"{deployment_id}\"")
            lines.append(f"      {LABEL_RELEASE_REVISION}: \"{release_revision}\"")
    if include_storage_init:
        lines.append("  storage-init:")
        lines.append(f"    image: {image_ids['api']}")
        lines.append("    pull_policy: never")
        if deployment_id is not None and release_revision is not None:
            lines.append("    labels:")
            lines.append(f"      {LABEL_DEPLOYMENT_ID}: \"{deployment_id}\"")
            lines.append(f"      {LABEL_RELEASE_REVISION}: \"{release_revision}\"")
    lines.append("")
    return "\n".join(lines)


def write_images_override(
    directory: Path,
    image_ids: dict[str, str],
    *,
    deployment_id: str | None = None,
    release_revision: str | None = None,
    include_delivery: bool = False,
    include_storage_init: bool = False,
) -> Path:
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / IMAGES_OVERRIDE_NAME
    text = render_images_override(
        image_ids,
        deployment_id=deployment_id,
        release_revision=release_revision,
        include_delivery=include_delivery,
        include_storage_init=include_storage_init,
    )
    if "postgres" in text.split("services:", 1)[-1].split("\n")[0:20]:
        # Belt-and-suspenders: body after services: must not define postgres.
        pass
    if re.search(r"(?m)^\s*postgres\s*:", text):
        raise OverrideError("override unexpectedly mentions postgres")
    atomic_write_text(path, text, mode=0o600)
    if not path.is_file():
        raise JournalIOError(f"failed to write override: {path}")
    return path
