"""Minimized yt-dlp-shaped fixtures (no signed/CDN URLs, no copyrighted blobs)."""

from __future__ import annotations

import json

VK_FIXTURE: dict[str, object] = {
    "id": "-123_456239017",
    "title": "Sample VK clip",
    "duration": 42,
    "extractor": "vk",
    "extractor_key": "vk",
    "webpage_url": "https://vk.com/video-123_456239017",
    "original_url": "https://vk.com/video-123_456239017",
    "formats": [
        {
            "format_id": "url720",
            "ext": "mp4",
            "width": 1280,
            "height": 720,
            "fps": 30,
            "vcodec": "avc1.64001F",
            "acodec": "mp4a.40.2",
            "filesize": 5_000_000,
            "url": "https://example.invalid/signed/PLACEHOLDER_NOT_REAL",
        },
        {
            "format_id": "url1080",
            "ext": "mp4",
            "width": 1920,
            "height": 1080,
            "fps": 30,
            "vcodec": "avc1.640028",
            "acodec": "mp4a.40.2",
            "filesize": 12_000_000,
            "url": "https://cdn.example.invalid/direct/PLACEHOLDER",
        },
        {
            "format_id": "url360",
            "ext": "mp4",
            "width": 640,
            "height": 360,
            "fps": 30,
            "vcodec": "avc1.4D401E",
            "acodec": "mp4a.40.2",
            "filesize": 2_000_000,
            "url": "https://example.invalid/360/PLACEHOLDER",
        },
        {
            "format_id": "dash-video",
            "ext": "mp4",
            "width": 1280,
            "height": 720,
            "fps": 30,
            "vcodec": "avc1.64001F",
            "acodec": "none",
            "filesize_approx": 4_000_000,
            "url": "https://example.invalid/vonly/PLACEHOLDER",
        },
        {
            "format_id": "dash-audio",
            "ext": "m4a",
            "vcodec": "none",
            "acodec": "mp4a.40.2",
            "filesize_approx": 500_000,
            "url": "https://example.invalid/aonly/PLACEHOLDER",
        },
    ],
}

RUTUBE_FIXTURE: dict[str, object] = {
    "id": "abc123def456",
    "title": "Sample Rutube video",
    "duration": 120,
    "extractor": "rutube",
    "extractor_key": "rutube",
    "webpage_url": "https://rutube.ru/video/abc123def456/",
    "original_url": "https://rutube.ru/video/abc123def456/",
    "formats": [
        {
            "format_id": "m3u8-720",
            "ext": "mp4",
            "width": 1280,
            "height": 720,
            "fps": 25,
            "vcodec": "avc1.64001F",
            "acodec": "mp4a.40.2",
            "filesize_approx": 8_000_000,
            "url": "https://rutube.example.invalid/hls/PLACEHOLDER.m3u8",
        },
        {
            "format_id": "m3u8-480",
            "ext": "mp4",
            "width": 854,
            "height": 480,
            "fps": 25,
            "vcodec": "avc1.4D401F",
            "acodec": "mp4a.40.2",
            "filesize_approx": 4_000_000,
            "url": "https://rutube.example.invalid/hls/PLACEHOLDER480.m3u8",
        },
    ],
}


# Live-shaped Yandex Preview → VK inspection: no progressive file, split A/V.
YANDEX_PREVIEW_VK_SPLIT_FIXTURE: dict[str, object] = {
    "id": "-123_456239017",
    "title": "Yandex preview sample",
    "duration": 58,
    "extractor": "vk",
    "extractor_key": "vk",
    "webpage_url": "https://vk.com/video-123_456239017",
    "original_url": "https://vk.com/video-123_456239017",
    "formats": [
        {
            "format_id": "hls-1080",
            "ext": "mp4",
            "width": 1920,
            "height": 1080,
            "fps": 30,
            "vcodec": "avc1.640028",
            "acodec": "none",
            "protocol": "m3u8_native",
            "filesize_approx": 18_000_000,
            "url": "https://example.invalid/hls/1080.m3u8",
        },
        {
            "format_id": "url1080",
            "ext": "mp4",
            "width": 1920,
            "height": 1080,
            "fps": 30,
            "vcodec": "avc1.640028",
            "acodec": "none",
            "protocol": "https",
            "filesize": 16_000_000,
            "url": "https://example.invalid/v/1080",
        },
        {
            "format_id": "url720",
            "ext": "mp4",
            "width": 1280,
            "height": 720,
            "fps": 30,
            "vcodec": "avc1.64001F",
            "acodec": "none",
            "protocol": "https",
            "filesize": 8_000_000,
            "url": "https://example.invalid/v/720",
        },
        {
            "format_id": "url240",
            "ext": "mp4",
            "width": 426,
            "height": 240,
            "fps": 30,
            "vcodec": "avc1.4D4015",
            "acodec": "none",
            "protocol": "https",
            "filesize": 900_000,
            "url": "https://example.invalid/v/240",
        },
        {
            "format_id": "url144",
            "ext": "mp4",
            "width": 256,
            "height": 144,
            "fps": 30,
            "vcodec": "avc1.4D400C",
            "acodec": "none",
            "protocol": "https",
            "filesize": 400_000,
            "url": "https://example.invalid/v/144",
        },
        {
            "format_id": "url480",
            "ext": "mp4",
            "width": 854,
            "height": 480,
            "fps": 30,
            "vcodec": "avc1.4D401F",
            "acodec": "none",
            "protocol": "https",
            "filesize": 4_000_000,
            "url": "https://example.invalid/v/480",
        },
        {
            "format_id": "url360",
            "ext": "mp4",
            "width": 640,
            "height": 360,
            "fps": 30,
            "vcodec": "avc1.4D401E",
            "acodec": "none",
            "protocol": "https",
            "filesize": 2_000_000,
            "url": "https://example.invalid/v/360",
        },
        {
            "format_id": "url360-dup",
            "ext": "mp4",
            "width": 640,
            "height": 360,
            "fps": 30,
            "vcodec": "avc1.4D401E",
            "acodec": "none",
            "protocol": "https",
            "filesize": 2_000_000,
            "url": "https://example.invalid/v/360-dup",
        },
        {
            "format_id": "audio-aac",
            "ext": "m4a",
            "vcodec": "none",
            "acodec": "mp4a.40.2",
            "protocol": "https",
            "filesize": 400_000,
            "url": "https://example.invalid/a/aac",
        },
        {
            "format_id": "audio-aac-hi",
            "ext": "m4a",
            "vcodec": "none",
            "acodec": "mp4a.40.2",
            "protocol": "https",
            "filesize": 800_000,
            "url": "https://example.invalid/a/aac-hi",
        },
        {
            "format_id": "audio-mp3",
            "ext": "mp3",
            "vcodec": "none",
            "acodec": "mp3",
            "protocol": "https",
            "filesize": 300_000,
            "url": "https://example.invalid/a/mp3",
        },
        {
            "format_id": "audio-opus",
            "ext": "webm",
            "vcodec": "none",
            "acodec": "opus",
            "protocol": "https",
            "filesize": 350_000,
            "url": "https://example.invalid/a/opus",
        },
        {
            "format_id": "drm-audio",
            "ext": "m4a",
            "vcodec": "none",
            "acodec": "mp4a.40.2",
            "protocol": "https",
            "has_drm": True,
            "filesize": 400_000,
            "url": "https://example.invalid/a/drm",
        },
        {
            "format_id": "unknown-video",
            "ext": "mp4",
            "width": 1280,
            "height": 720,
            "fps": 30,
            "vcodec": "hevc",
            "acodec": "none",
            "protocol": "https",
            "filesize": 7_000_000,
            "url": "https://example.invalid/v/hevc",
        },
        {
            "format_id": "oversized",
            "ext": "mp4",
            "width": 1280,
            "height": 720,
            "fps": 30,
            "vcodec": "avc1.64001F",
            "acodec": "none",
            "protocol": "https",
            "filesize": 9_999_999_999,
            "url": "https://example.invalid/v/huge",
        },
        {
            "format_id": "malformed",
            "ext": "mp4",
            "width": "wide",
            "height": 480,
            "vcodec": "avc1",
            "acodec": "none",
            "url": "https://example.invalid/v/bad",
        },
    ],
}


def dumps_fixture(payload: dict[str, object]) -> bytes:
    return json.dumps(payload, separators=(",", ":"), ensure_ascii=True).encode("utf-8")
